### ISSUE TITLE
network wire connection point issue

### ISSUE THREAD

**Issue by CaitSith2** [GregorSamsanite/nullius#11]
![image](https://user-images.githubusercontent.com/79097/198193563-de2c61c3-80c4-483d-a66c-ff0a952e3dd9.png)

This seems to have not been set to line up with the Hangar 4's reduced size.  Looks visually wrong.

**Comment by GregorSamsanite** [comment]
Yeah that's definitely not right.  I'll fix it.

**Comment by CaitSith2** [comment]
Also for a suggestion, why not allow me to connect a network wire to the relays/chargers.  My current blue prints require me to use hangars for checking for multiple things on the logistic network at once, but with hangars, that means the construction bots WILL park at the hangar as the location is built.   I am aware that both the relays and chargers both use the roboport prototypes.

**Comment by GregorSamsanite** [comment]
This is now fixed in the latest update.  Yes, it's also added to relays now.  I think that makes more sense than chargers, given the role of each building.  The holdup before was that specifying the circuit connection positions is done through a weird system, but once I had to figure out how to use it for hangar 4, it became easy to make it work for relay too.
